/*
 * Copyright (C) 2005, The Beangle Software.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: account.proto
// Protobuf Java Version: 4.28.2

package org.beangle.serializer.protobuf;

public final class AccountProtobuf {
  private AccountProtobuf() {
  }

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      AccountProtobuf.class.getName());
  }

  public static void registerAllExtensions(
    com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
    com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
      (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface AccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Account)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
    getNameBytes();

    /**
     * <code>string description = 2;</code>
     *
     * @return The description.
     */
    java.lang.String getDescription();

    /**
     * <code>string description = 2;</code>
     *
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
    getDescriptionBytes();

    /**
     * <code>string remoteToken = 3;</code>
     *
     * @return The remoteToken.
     */
    java.lang.String getRemoteToken();

    /**
     * <code>string remoteToken = 3;</code>
     *
     * @return The bytes for remoteToken.
     */
    com.google.protobuf.ByteString
    getRemoteTokenBytes();

    /**
     * <code>int32 status = 4;</code>
     *
     * @return The status.
     */
    int getStatus();

    /**
     * <code>string authorities = 5;</code>
     *
     * @return The authorities.
     */
    java.lang.String getAuthorities();

    /**
     * <code>string authorities = 5;</code>
     *
     * @return The bytes for authorities.
     */
    com.google.protobuf.ByteString
    getAuthoritiesBytes();

    /**
     * <code>string permissions = 6;</code>
     *
     * @return The permissions.
     */
    java.lang.String getPermissions();

    /**
     * <code>string permissions = 6;</code>
     *
     * @return The bytes for permissions.
     */
    com.google.protobuf.ByteString
    getPermissionsBytes();

    /**
     * <code>map&lt;string, string&gt; details = 7;</code>
     */
    int getDetailsCount();

    /**
     * <code>map&lt;string, string&gt; details = 7;</code>
     */
    boolean containsDetails(
      java.lang.String key);

    /**
     * Use {@link #getDetailsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getDetails();

    /**
     * <code>map&lt;string, string&gt; details = 7;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getDetailsMap();

    /**
     * <code>map&lt;string, string&gt; details = 7;</code>
     */
    /* nullable */
    java.lang.String getDetailsOrDefault(
      java.lang.String key,
      /* nullable */
      java.lang.String defaultValue);

    /**
     * <code>map&lt;string, string&gt; details = 7;</code>
     */
    java.lang.String getDetailsOrThrow(
      java.lang.String key);
  }

  /**
   * Protobuf type {@code Account}
   */
  public static final class Account extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Account)
    AccountOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        Account.class.getName());
    }

    // Use Account.newBuilder() to construct.
    private Account(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }

    private Account() {
      name_ = "";
      description_ = "";
      remoteToken_ = "";
      authorities_ = "";
      permissions_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return org.beangle.serializer.protobuf.AccountProtobuf.internal_static_Account_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
      switch (number) {
        case 7:
          return internalGetDetails();
        default:
          throw new RuntimeException(
            "Invalid map field number: " + number);
      }
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return org.beangle.serializer.protobuf.AccountProtobuf.internal_static_Account_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
          org.beangle.serializer.protobuf.AccountProtobuf.Account.class, org.beangle.serializer.protobuf.AccountProtobuf.Account.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";

    /**
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }

    /**
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";

    /**
     * <code>string description = 2;</code>
     *
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }

    /**
     * <code>string description = 2;</code>
     *
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMOTETOKEN_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object remoteToken_ = "";

    /**
     * <code>string remoteToken = 3;</code>
     *
     * @return The remoteToken.
     */
    @java.lang.Override
    public java.lang.String getRemoteToken() {
      java.lang.Object ref = remoteToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remoteToken_ = s;
        return s;
      }
    }

    /**
     * <code>string remoteToken = 3;</code>
     *
     * @return The bytes for remoteToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getRemoteTokenBytes() {
      java.lang.Object ref = remoteToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        remoteToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_ = 0;

    /**
     * <code>int32 status = 4;</code>
     *
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    public static final int AUTHORITIES_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object authorities_ = "";

    /**
     * <code>string authorities = 5;</code>
     *
     * @return The authorities.
     */
    @java.lang.Override
    public java.lang.String getAuthorities() {
      java.lang.Object ref = authorities_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authorities_ = s;
        return s;
      }
    }

    /**
     * <code>string authorities = 5;</code>
     *
     * @return The bytes for authorities.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getAuthoritiesBytes() {
      java.lang.Object ref = authorities_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        authorities_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERMISSIONS_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object permissions_ = "";

    /**
     * <code>string permissions = 6;</code>
     *
     * @return The permissions.
     */
    @java.lang.Override
    public java.lang.String getPermissions() {
      java.lang.Object ref = permissions_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        permissions_ = s;
        return s;
      }
    }

    /**
     * <code>string permissions = 6;</code>
     *
     * @return The bytes for permissions.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getPermissionsBytes() {
      java.lang.Object ref = permissions_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        permissions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DETAILS_FIELD_NUMBER = 7;

    private static final class DetailsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
        com.google.protobuf.MapEntry
          .<java.lang.String, java.lang.String>newDefaultInstance(
            org.beangle.serializer.protobuf.AccountProtobuf.internal_static_Account_DetailsEntry_descriptor,
            com.google.protobuf.WireFormat.FieldType.STRING,
            "",
            com.google.protobuf.WireFormat.FieldType.STRING,
            "");
    }

    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> details_;

    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetDetails() {
      if (details_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
          DetailsDefaultEntryHolder.defaultEntry);
      }
      return details_;
    }

    public int getDetailsCount() {
      return internalGetDetails().getMap().size();
    }

    /**
     * <code>map&lt;string, string&gt; details = 7;</code>
     */
    @java.lang.Override
    public boolean containsDetails(
      java.lang.String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      return internalGetDetails().getMap().containsKey(key);
    }

    /**
     * Use {@link #getDetailsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getDetails() {
      return getDetailsMap();
    }

    /**
     * <code>map&lt;string, string&gt; details = 7;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getDetailsMap() {
      return internalGetDetails().getMap();
    }

    /**
     * <code>map&lt;string, string&gt; details = 7;</code>
     */
    @java.lang.Override
    public /* nullable */
    java.lang.String getDetailsOrDefault(
      java.lang.String key,
      /* nullable */
      java.lang.String defaultValue) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      java.util.Map<java.lang.String, java.lang.String> map =
        internalGetDetails().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;string, string&gt; details = 7;</code>
     */
    @java.lang.Override
    public java.lang.String getDetailsOrThrow(
      java.lang.String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      java.util.Map<java.lang.String, java.lang.String> map =
        internalGetDetails().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, description_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(remoteToken_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, remoteToken_);
      }
      if (status_ != 0) {
        output.writeInt32(4, status_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(authorities_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, authorities_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(permissions_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, permissions_);
      }
      com.google.protobuf.GeneratedMessage
        .serializeStringMapTo(
          output,
          internalGetDetails(),
          DetailsDefaultEntryHolder.defaultEntry,
          7);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, description_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(remoteToken_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, remoteToken_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, status_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(authorities_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, authorities_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(permissions_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, permissions_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
        : internalGetDetails().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
          details__ = DetailsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, details__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof org.beangle.serializer.protobuf.AccountProtobuf.Account)) {
        return super.equals(obj);
      }
      org.beangle.serializer.protobuf.AccountProtobuf.Account other = (org.beangle.serializer.protobuf.AccountProtobuf.Account) obj;

      if (!getName()
        .equals(other.getName())) return false;
      if (!getDescription()
        .equals(other.getDescription())) return false;
      if (!getRemoteToken()
        .equals(other.getRemoteToken())) return false;
      if (getStatus()
        != other.getStatus()) return false;
      if (!getAuthorities()
        .equals(other.getAuthorities())) return false;
      if (!getPermissions()
        .equals(other.getPermissions())) return false;
      if (!internalGetDetails().equals(
        other.internalGetDetails())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + REMOTETOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getRemoteToken().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + AUTHORITIES_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorities().hashCode();
      hash = (37 * hash) + PERMISSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getPermissions().hashCode();
      if (!internalGetDetails().getMap().isEmpty()) {
        hash = (37 * hash) + DETAILS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetDetails().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.beangle.serializer.protobuf.AccountProtobuf.Account parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static org.beangle.serializer.protobuf.AccountProtobuf.Account parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.beangle.serializer.protobuf.AccountProtobuf.Account parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static org.beangle.serializer.protobuf.AccountProtobuf.Account parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.beangle.serializer.protobuf.AccountProtobuf.Account parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static org.beangle.serializer.protobuf.AccountProtobuf.Account parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.beangle.serializer.protobuf.AccountProtobuf.Account parseFrom(java.io.InputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
    }

    public static org.beangle.serializer.protobuf.AccountProtobuf.Account parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.beangle.serializer.protobuf.AccountProtobuf.Account parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.beangle.serializer.protobuf.AccountProtobuf.Account parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.beangle.serializer.protobuf.AccountProtobuf.Account parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
    }

    public static org.beangle.serializer.protobuf.AccountProtobuf.Account parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(org.beangle.serializer.protobuf.AccountProtobuf.Account prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code Account}
     */
    public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Account)
      org.beangle.serializer.protobuf.AccountProtobuf.AccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return org.beangle.serializer.protobuf.AccountProtobuf.internal_static_Account_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
        switch (number) {
          case 7:
            return internalGetDetails();
          default:
            throw new RuntimeException(
              "Invalid map field number: " + number);
        }
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
        switch (number) {
          case 7:
            return internalGetMutableDetails();
          default:
            throw new RuntimeException(
              "Invalid map field number: " + number);
        }
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return org.beangle.serializer.protobuf.AccountProtobuf.internal_static_Account_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
            org.beangle.serializer.protobuf.AccountProtobuf.Account.class, org.beangle.serializer.protobuf.AccountProtobuf.Account.Builder.class);
      }

      // Construct using org.beangle.serializer.protobuf.AccountProtobuf.Account.newBuilder()
      private Builder() {

      }

      private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        description_ = "";
        remoteToken_ = "";
        status_ = 0;
        authorities_ = "";
        permissions_ = "";
        internalGetMutableDetails().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return org.beangle.serializer.protobuf.AccountProtobuf.internal_static_Account_descriptor;
      }

      @java.lang.Override
      public org.beangle.serializer.protobuf.AccountProtobuf.Account getDefaultInstanceForType() {
        return org.beangle.serializer.protobuf.AccountProtobuf.Account.getDefaultInstance();
      }

      @java.lang.Override
      public org.beangle.serializer.protobuf.AccountProtobuf.Account build() {
        org.beangle.serializer.protobuf.AccountProtobuf.Account result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.beangle.serializer.protobuf.AccountProtobuf.Account buildPartial() {
        org.beangle.serializer.protobuf.AccountProtobuf.Account result = new org.beangle.serializer.protobuf.AccountProtobuf.Account(this);
        if (bitField0_ != 0) {
          buildPartial0(result);
        }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.beangle.serializer.protobuf.AccountProtobuf.Account result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.description_ = description_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.remoteToken_ = remoteToken_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.authorities_ = authorities_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.permissions_ = permissions_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.details_ = internalGetDetails();
          result.details_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.beangle.serializer.protobuf.AccountProtobuf.Account) {
          return mergeFrom((org.beangle.serializer.protobuf.AccountProtobuf.Account) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.beangle.serializer.protobuf.AccountProtobuf.Account other) {
        if (other == org.beangle.serializer.protobuf.AccountProtobuf.Account.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getRemoteToken().isEmpty()) {
          remoteToken_ = other.remoteToken_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getAuthorities().isEmpty()) {
          authorities_ = other.authorities_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getPermissions().isEmpty()) {
          permissions_ = other.permissions_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        internalGetMutableDetails().mergeFrom(
          other.internalGetDetails());
        bitField0_ |= 0x00000040;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                remoteToken_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                status_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                authorities_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                permissions_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                  details__ = input.readMessage(
                  DetailsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableDetails().getMutableMap().put(
                  details__.getKey(), details__.getValue());
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int bitField0_;

      private java.lang.Object name_ = "";

      /**
       * <code>string name = 1;</code>
       *
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string name = 1;</code>
       *
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
      getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string name = 1;</code>
       *
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
        java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      /**
       * <code>string name = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      /**
       * <code>string name = 1;</code>
       *
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";

      /**
       * <code>string description = 2;</code>
       *
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string description = 2;</code>
       *
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
      getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string description = 2;</code>
       *
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
        java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        description_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      /**
       * <code>string description = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      /**
       * <code>string description = 2;</code>
       *
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object remoteToken_ = "";

      /**
       * <code>string remoteToken = 3;</code>
       *
       * @return The remoteToken.
       */
      public java.lang.String getRemoteToken() {
        java.lang.Object ref = remoteToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          remoteToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string remoteToken = 3;</code>
       *
       * @return The bytes for remoteToken.
       */
      public com.google.protobuf.ByteString
      getRemoteTokenBytes() {
        java.lang.Object ref = remoteToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
          remoteToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string remoteToken = 3;</code>
       *
       * @param value The remoteToken to set.
       * @return This builder for chaining.
       */
      public Builder setRemoteToken(
        java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        remoteToken_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      /**
       * <code>string remoteToken = 3;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearRemoteToken() {
        remoteToken_ = getDefaultInstance().getRemoteToken();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      /**
       * <code>string remoteToken = 3;</code>
       *
       * @param value The bytes for remoteToken to set.
       * @return This builder for chaining.
       */
      public Builder setRemoteTokenBytes(
        com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        remoteToken_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int status_;

      /**
       * <code>int32 status = 4;</code>
       *
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }

      /**
       * <code>int32 status = 4;</code>
       *
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {

        status_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      /**
       * <code>int32 status = 4;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object authorities_ = "";

      /**
       * <code>string authorities = 5;</code>
       *
       * @return The authorities.
       */
      public java.lang.String getAuthorities() {
        java.lang.Object ref = authorities_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authorities_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string authorities = 5;</code>
       *
       * @return The bytes for authorities.
       */
      public com.google.protobuf.ByteString
      getAuthoritiesBytes() {
        java.lang.Object ref = authorities_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
          authorities_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string authorities = 5;</code>
       *
       * @param value The authorities to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorities(
        java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        authorities_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      /**
       * <code>string authorities = 5;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearAuthorities() {
        authorities_ = getDefaultInstance().getAuthorities();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      /**
       * <code>string authorities = 5;</code>
       *
       * @param value The bytes for authorities to set.
       * @return This builder for chaining.
       */
      public Builder setAuthoritiesBytes(
        com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        authorities_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object permissions_ = "";

      /**
       * <code>string permissions = 6;</code>
       *
       * @return The permissions.
       */
      public java.lang.String getPermissions() {
        java.lang.Object ref = permissions_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          permissions_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string permissions = 6;</code>
       *
       * @return The bytes for permissions.
       */
      public com.google.protobuf.ByteString
      getPermissionsBytes() {
        java.lang.Object ref = permissions_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
          permissions_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string permissions = 6;</code>
       *
       * @param value The permissions to set.
       * @return This builder for chaining.
       */
      public Builder setPermissions(
        java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        permissions_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      /**
       * <code>string permissions = 6;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearPermissions() {
        permissions_ = getDefaultInstance().getPermissions();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      /**
       * <code>string permissions = 6;</code>
       *
       * @param value The bytes for permissions to set.
       * @return This builder for chaining.
       */
      public Builder setPermissionsBytes(
        com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        permissions_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> details_;

      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetDetails() {
        if (details_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
            DetailsDefaultEntryHolder.defaultEntry);
        }
        return details_;
      }

      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableDetails() {
        if (details_ == null) {
          details_ = com.google.protobuf.MapField.newMapField(
            DetailsDefaultEntryHolder.defaultEntry);
        }
        if (!details_.isMutable()) {
          details_ = details_.copy();
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return details_;
      }

      public int getDetailsCount() {
        return internalGetDetails().getMap().size();
      }

      /**
       * <code>map&lt;string, string&gt; details = 7;</code>
       */
      @java.lang.Override
      public boolean containsDetails(
        java.lang.String key) {
        if (key == null) {
          throw new NullPointerException("map key");
        }
        return internalGetDetails().getMap().containsKey(key);
      }

      /**
       * Use {@link #getDetailsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getDetails() {
        return getDetailsMap();
      }

      /**
       * <code>map&lt;string, string&gt; details = 7;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getDetailsMap() {
        return internalGetDetails().getMap();
      }

      /**
       * <code>map&lt;string, string&gt; details = 7;</code>
       */
      @java.lang.Override
      public /* nullable */
      java.lang.String getDetailsOrDefault(
        java.lang.String key,
        /* nullable */
        java.lang.String defaultValue) {
        if (key == null) {
          throw new NullPointerException("map key");
        }
        java.util.Map<java.lang.String, java.lang.String> map =
          internalGetDetails().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }

      /**
       * <code>map&lt;string, string&gt; details = 7;</code>
       */
      @java.lang.Override
      public java.lang.String getDetailsOrThrow(
        java.lang.String key) {
        if (key == null) {
          throw new NullPointerException("map key");
        }
        java.util.Map<java.lang.String, java.lang.String> map =
          internalGetDetails().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearDetails() {
        bitField0_ = (bitField0_ & ~0x00000040);
        internalGetMutableDetails().getMutableMap()
          .clear();
        return this;
      }

      /**
       * <code>map&lt;string, string&gt; details = 7;</code>
       */
      public Builder removeDetails(
        java.lang.String key) {
        if (key == null) {
          throw new NullPointerException("map key");
        }
        internalGetMutableDetails().getMutableMap()
          .remove(key);
        return this;
      }

      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableDetails() {
        bitField0_ |= 0x00000040;
        return internalGetMutableDetails().getMutableMap();
      }

      /**
       * <code>map&lt;string, string&gt; details = 7;</code>
       */
      public Builder putDetails(
        java.lang.String key,
        java.lang.String value) {
        if (key == null) {
          throw new NullPointerException("map key");
        }
        if (value == null) {
          throw new NullPointerException("map value");
        }
        internalGetMutableDetails().getMutableMap()
          .put(key, value);
        bitField0_ |= 0x00000040;
        return this;
      }

      /**
       * <code>map&lt;string, string&gt; details = 7;</code>
       */
      public Builder putAllDetails(
        java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableDetails().getMutableMap()
          .putAll(values);
        bitField0_ |= 0x00000040;
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Account)
    }

    // @@protoc_insertion_point(class_scope:Account)
    private static final org.beangle.serializer.protobuf.AccountProtobuf.Account DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new org.beangle.serializer.protobuf.AccountProtobuf.Account();
    }

    public static org.beangle.serializer.protobuf.AccountProtobuf.Account getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Account>
      PARSER = new com.google.protobuf.AbstractParser<Account>() {
      @java.lang.Override
      public Account parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Account> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Account> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.beangle.serializer.protobuf.AccountProtobuf.Account getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Account_descriptor;
  private static final
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internal_static_Account_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Account_DetailsEntry_descriptor;
  private static final
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internal_static_Account_DetailsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor
    descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\raccount.proto\"\323\001\n\007Account\022\014\n\004name\030\001 \001(" +
        "\t\022\023\n\013description\030\002 \001(\t\022\023\n\013remoteToken\030\003 " +
        "\001(\t\022\016\n\006status\030\004 \001(\005\022\023\n\013authorities\030\005 \001(\t" +
        "\022\023\n\013permissions\030\006 \001(\t\022&\n\007details\030\007 \003(\0132\025" +
        ".Account.DetailsEntry\032.\n\014DetailsEntry\022\013\n" +
        "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B2\n\037org.bea" +
        "ngle.serializer.protobufB\017AccountProtobu" +
        "fb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[]{
        });
    internal_static_Account_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Account_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
      internal_static_Account_descriptor,
      new java.lang.String[]{"Name", "Description", "RemoteToken", "Status", "Authorities", "Permissions", "Details",});
    internal_static_Account_DetailsEntry_descriptor =
      internal_static_Account_descriptor.getNestedTypes().get(0);
    internal_static_Account_DetailsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
      internal_static_Account_DetailsEntry_descriptor,
      new java.lang.String[]{"Key", "Value",});
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
